import Head from 'next/head'
//import Image from 'next/image'
import App from '../components/App'
import Design from '../components/Design'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App/>
      {/* <Design display={"design-mobile-restart"}/> */}
    </>
  )
}
